version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: aimi_postgres
    environment:
      POSTGRES_DB: aimi
      POSTGRES_USER: aimi
      POSTGRES_PASSWORD: aimi
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: aimi_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
